### ISSUE TITLE
Wear Noti Demo Issue

### ISSUE THREAD

**Issue by meloveself94** [JimSeker/wearable#1]
I've tried the wear noti demo app but notifications only show up on my device but not on my android wear. Are there any additional configurations I should do besides just running the app on my phone?

**Comment by meloveself94** [comment]
Sorry for closing and re-opening the issue, it's my mistake that I did not enable notification for my android wear. Another question is may I know how to vibrate the android wear on notification receive? This is because I wouldn't be able to know if I've receive any notification on my android wear. Thank You and Sorry for inconvenience.

**Comment by JimSeker** [comment]
The wear should mimic the notification for the phone for the most part.    Not all of my examples vibrate. 
There needs to be line like .setVibrate(new long[]{1000, 1000, 1000, 1000, 1000, 1000})  and the channel has to allow vibration, plus the activity has to have vibrate permission as well.  looks like I left it off the WearNotiDemo.
