### ISSUE TITLE
Examples for heart rate collection

### ISSUE THREAD

**Issue by shllybkwrm** [JimSeker/wearable#3]
Hi!  Your examples are super helpful.  I was just wondering if you had anything for more advanced features like the heart rate sensor, accelerometer / step counter, etc.  Thanks in advance!

**Comment by JimSeker** [comment]
I don't have any devices that I can test for heart rate.  I have one with a step counter for the wear os.

**Comment by JimSeker** [comment]
actually I don't.  sorry, I had an example I was working on, but it was never finished.   I have step counters in with google fit. https://github.com/JimSeker/googleplayAPI   google's permissions system may prevent you for actually the data in a raw format as I wanted to with the step counter in the original unfinished example.
